# Site
encoding: utf-8
name: "justgogooma"
title: "Just Go구마 | 고구마 덕후를 위한 가이드"
description: "고구마 덕후를 위한 가이드북"
logo: 'assets/images/logo2.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  #justgogooma:
    #name: justgogooma
    #display_name: gogooma
    #gravatar: e56154546cf4be74e393c62d1ae9f9d4
    #email: wowthemesnet@gmail.com
    #web: https://mygogooma.com
    #twitter: https://twitter.com/justgogooma
    #description: "고구마를 사랑하는 고구마덕후"
  justgogooma:
    name: "저스트고구마"
    display_name: "저스트고구마"
    avatar: 'assets/images/avatar.png'
    #gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: gogooma23@gmail.com
    web: https://mygogooma.com
    twitter: https://twitter.com/justgogooma
    description: "고구마를 사랑하는 고구마덕후"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
